name: Check Branch Lock
on: workflow_dispatch

jobs:
  check-branch-lock:
    name: Check if Lock Flag is set
    runs-on: ubuntu-latest

    steps:
    - uses: dawidd6/action-download-artifact@v6
      with:
        name: lock-flag
        workflow: lock-branch.yml
        path: .
        # locks branch for 7 days
        if_no_artifact_found: ignore
    - run: |
        # Check if the file 'locked.txt' exists
        if [ -f "locked.txt" ]; then
            # Check the contents of the file
            if grep -q "LOCKED" "locked.txt"; then
                echo "The file 'locked.txt' contains 'LOCKED'. Failing."
                exit 1
            else
                echo "The file 'locked.txt' does not contain 'LOCKED'. Passing."
                exit 0
            fi
        else
            echo "The file 'locked.txt' does not exist. Passing."
            exit 0
        fi