name: Check Branch Lock
on: workflow_dispatch

jobs:
  check-branch-lock:
    name: Check if Lock Flag is set
    runs-on: ubuntu-latest

    steps:
    - uses: dawidd6/action-download-artifact@v6
      with:
        name: lock-flag
        workflow: lock-branch.yml
        path: lock-flag
        # locks branch for 7 days
        if_no_artifact_found: ignore
    - run: ls lock-flag