name: Check Branch Lock
on: workflow_dispatch

#on:
#  pull_request:
#    branches: [master]
#    types: [opened, reopened, synchronize, labeled]

jobs:
  check-branch-lock:
    # Do not run this check if the pull request labels include "bypass-code-freeze"
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'bypass-code-freeze') }}

    name: Check if Lock Flag is set
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');

            console.log("Finding Last run of lock-branch")
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "lock-branch.yml",
              status: "success"
            });
            const lastRun = runs.data.workflow_runs.reduce(function(prev, current) {
                return (prev.run_number > current.run_number) ? prev : current
            })
            console.log("Last run of lock-branch.yml: " + lastRun.html_url)            
            
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                           owner: context.repo.owner,
                           repo: context.repo.repo,
                           run_id: lastRun.id,
                        });
            console.log("Found artifacts:")
            console.log(artifacts.data.artifacts)
            const [lockFile] = artifacts.data.artifacts.filter((artifact) =>
              artifact.name == "lock-flag");
            const expirationDate = new Date(lockFile.expires_at);
            if (expirationDate <  Date.now()) {
              console.log("Artifact expired, no lock")
              return true
            }
            const downloadWorkflow = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: lockFile.id,
               archive_format: "zip",
            });
            fs.writeFileSync("lock-flag.zip", Buffer.from(downloadWorkflow.data));
      - name: Unzip the output of 'main'
        run:  |
          if [ -f "lock-flag.zip" ]; then
            unzip lock-flag.zip
          fi
      - name: Check file
        run: |
          # Check if the file 'lock-flag.json' exists
          if [ -f "lock-flag.json" ]; then
              # Check the contents of the file
            if jq -e '.locked' lock-flag.json | grep -q 'true'; then
              echo "The locked flag is true, branch is locked"
              exit 1
            else
              echo "The locked flag is false, branch is open"
              exit 0
            fi
          else
              echo "The file 'lock-flag.json' does not exist. Passing."
              exit 0
          fi
