name: Check Branch Lock
on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, labeled]

jobs:
  check-branch-lock:
    name: Check if Lock Flag is set
    runs-on: ubuntu-latest

    if: !contains(github.event.pull_request.labels.*.name, 'bypass-code-freeze')

    steps:
    - uses: dawidd6/action-download-artifact@v6
      with:
        name: lock-flag
        workflow: lock-branch.yml
        # locks branch for 7 days
        if_no_artifact_found: ignore
    - run: |
    - run: |
        # Check if the file 'locked.txt' exists
        if [ -f "lock-flag.txt" ]; then
            # Check the contents of the file
            if grep -q "LOCK" "lock-flag.txt"; then
                echo "The file 'lock-flag.txt' contains 'LOCK'. Failing."
                exit 1
            else
                echo "The file 'lock-flag.txt' does not contain 'LOCK'. Passing."
                exit 0
            fi
        else
            echo "The file 'lock-flag.txt' does not exist. Passing."
            exit 0
        fi