name: Lock / Unlock Branch
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Lock or OPEN'
        required: true
        default: 'LOCK'
        type: choice
        options:
          - LOCK
          - OPEN


jobs:
  upload-flag:
    name: Upload a flag to github artifacts to lock a branch
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p path/to/artifact
    - run: echo $ACTION > lock-flag.txt
      env:
        ACTION: ${{ inputs.action }}
    - uses: actions/upload-artifact@v4
      with:
        name: lock-flag
        path: lock-flag.txt
        # locks branch for 7 days
        retention-days: 7