name: Lock / Unlock Branch
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Lock or OPEN'
        required: true
        default: 'LOCK'
        type: choice
        options:
          - LOCK
          - OPEN


jobs:
  upload-flag:
    name: Upload a flag to github artifacts to lock a branch
    runs-on: ubuntu-latest

    steps:
      - env:
          ACTION: ${{ inputs.action }}
        run: |
          # Check the value of the ACTION environment variable
          if [ "$ACTION" == "LOCK" ]; then
            LOCKED=true
          else
            LOCKED=false
          fi

          # Create JSON content and write to a file using jq
          echo "{\"locked\": $LOCKED}" | jq '.' > lock-flag.json

      - uses: actions/upload-artifact@v4
        with:
          name: lock-flag
          path: lock-flag.json
          # locks branch for 7 days
          retention-days: 7
