name: Unlock Branch
on: workflow_dispatch

jobs:
  upload-flag:
    name: Upload a flag to github artifacts to lock a branch
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p path/to/artifact
    - run: echo "OPEN" > lock-flag.txt
    - uses: actions/upload-artifact@v4
      with:
        name: lock-flag
        path: lock-flag.txt
        # Short retention, missing file is interpreted as unlocked
        retention-days: 1